import fs from 'fs';
import path from 'path';
import type { Plugin } from 'vite';

export function generatePostsList(): Plugin {
  return {
    name: 'vite-plugin-generate-posts',
    async configResolved() {
      const postsDir = path.resolve('posts');
      const files = fs.readdirSync(postsDir).filter(file => file.endsWith('.md'));

      const posts = files.map(file => file.replace('.md', ''));

      const output = `// Auto-generated by vite-plugin-generate-posts
export const posts = ${JSON.stringify(posts, null, 2)};
`;

      fs.writeFileSync(path.resolve('src/lib/posts.ts'), output);
      console.log('✨ Generated src/lib/posts.ts');
    }
  };
}
